### PR TITLE
Add Before/After attributes for unit-test.

### PR DESCRIPTION
**Pull request by laneser**
Sorry for empty description.

Those are hooks attributes for unit-test.

please reference for specflow http://specflow.org/documentation/Hooks/

### CODE REVIEW

**Comment by ttutisani** [comment]
Hi. Why do you think this feature is necessary? What's the use case?
Nobody has asked about this yet. So I assume you need it.
Can you please describe for what you need it specifically?

**Comment by laneser** [comment]
For those unit-test which need initialization or destruction functions,
such as database creation and cleanup, we put those code in [BeforeScenario] and [AfterScenario].

I will not feel  frustrated if you reject the feature, then I will use my forked project.
Thanks for your patient!

**Comment by ttutisani** [comment]
Thanks for clarifying!

Initialization code should go into constructor of the tester class (one that derives from `Feature`). Or, if you have an advanced case, you can use Collection Fixture from Xunit, which supports both setup and tear down methods. You can read about this here for example: https://stackoverflow.com/questions/12976319/xunit-net-global-setup-teardown

At this point, I would have to restrain from merging this feature. If I see a need for such functionality in the future, clearly from feature/scenario (Gherkin) test standpoint, then I will come back to this.
Sorry!

But if you think I'm misunderstanding something, please do let me know.
As I said, for what you described, Xunit has better ways (Collection Fixture), so I don't think I need to support something in addition.

**Comment by laneser** [comment]
Collection Fixtures in xunit does matched the use case.
But I failed to get ITest at Construction...
When I want ITest to do show logs or do something about during a  Feature class construction, the Output is null...

```
            var type = Output.GetType();
            var testMember = type.GetField("test", BindingFlags.Instance | BindingFlags.NonPublic);
            var test = (ITest)testMember.GetValue(Output);
```

But [BeforeScenario] case, I can get ITest instance to do what I want.

**Comment by ttutisani** [comment]
Output is null because I assign to Output after constructor executes.

But, if you want Output to be not null, simply add `ITestOutputHelper` as your constructor parameter.
When constructor runs, use the parameter value, not Output property.

e.g.:

```C#
public sealed class MyFeature : Feature
{
    public MyFeature(ITestOutputHelper output2)
    {
        // output2 is not null, Output is null.
        var type = output2.GetType();
    }
}
```

**Comment by ttutisani** [comment]
Closing as out of scope. Thanks anyway for the effort!

**Pull request closed without merging**
