### PR TITLE
Test output without ctor param.

### PR DESCRIPTION
**Pull request by ttutisani**
Basically, this is a result of couple of days of research and dig into xunit base.
Now I'm able to see test steps output even without needing to have a constructor with test output helper argument.
Furthermore, derived class can either use the Output property from the base class, or it can even inject the ITestOutputHelper, which will be the exact same instance as the Output property. That ensures that the output messages from both the derived class as well as the Feature class get merged into the same chunk - just as a consumer would expect.

@ChristianPejrup FYI, in case you want to glance too.

Thanks both!

### CODE REVIEW

**Comment by ttutisani** [comment]
Oh and, BTW, it works fine without app.config XML file too. I hope it's not my machine acting weird because it works and shows output just fine.

**Comment by ChristianPejrup** [comment]
Sounds like a really good and solid change to align the Gherkin extension for xUnit with the core framework.

I must admit that I don't know enough about the xUnit stack to give good feedback on that part of the implementation.

For the implementation of InvokeTestAsync I'm wondering if it wouldn't make sense to have a wrapper around the _testOutputHelper to handle most of the initialization logic? - this could potentially eliminate the if's in InvokeTestAsync and make the method a bit more focused around the test invocation.

**Comment by ttutisani** [comment]
Yes, let me think about wrapping the test helper for initialize/uninitialize. Also, I want to make those all new classes internal, so that consumers don't get distracted when they browse the namespace using intellisense.

**Comment by ttutisani** [comment]
So, updates on this PR:
- Made classes internal.
- It didn't make much sense to wrap the ownership of the test output, just because it's one place, and it's kind of already wrapped. I tried to do that but seemed like replacing apple with apple. Maybe some other time when this becomes a reusable thing at least.

Also, I noticed that the steps after the failed one were not part of the output. That may be somewhat misleading to the readers of the output. Steps are there but they are not even acknowledged.
So, I added them to the output as SKIPPED. That way, all steps are in the output, but if any one of them fails, next ones are skipped but still mentioned. I think this can be useful to show to non-developers, because that explains what all the things could have happened next if not the failure.
I hope this is fine. @csurfleet what do you say? you needed the output in the first place.

**Comment by csurfleet** [comment]
Yeah that's a nice little addition. I'll get the code down and add an example with all 3 to my readme instead of just passed and failed. Cheers!

**Pull request merged**
