### PR TITLE
Cucumber expressions documentation

### PR DESCRIPTION
**Pull request by JornWildt**
Documenting cucumber expressions (including support for single quote strings).

### CODE REVIEW

**Comment by ttutisani** [comment]
I don't know why, but in this PR, I see a lot of things besides the documentation (see above, files changed - 10). Maybe because you reused the branch that you previously had. Please keep in mind that I squash-merged the cucumber expressions branch previously. So because now the commits are different between the branches, the same old changes are again showing up. To fix this, one way would be to create the branch out of the `ttutisani:master` and then only apply md file changes to that branch. Don't create a branch out of your own branches, because the commits differ.

**Comment by ttutisani** [comment]
Also see below:
image

**Comment by JornWildt** [comment]
Hmm, not sure what the problem comes from, my Git-Fu is not especially good. Will take a look at it.

**Comment by JornWildt** [comment]
Could it be that you need to merge the two other PR's first, as they are submitted before this PR?

**Comment by JornWildt** [comment]
Okay, tried to "fetch upstream" in GitHub. Them pull to local dev-machine. Then merge into this branche (and the other two branches) and then push that.

Does it work now?

**Comment by ttutisani** [comment]
Yes, that worked. I just merged one of the PRs, so can you please repeat those steps for this branch?

**Comment by JornWildt** [comment]
> can you please repeat those steps for this branch?

I believe I have done that for all three branches.

**Comment by ttutisani** [comment]
Yes, you did. I merged the single quotes PR after you did that. So the branch became out of date again.

**Comment by ttutisani** [comment]
Actually, I guess I could do it myself too. I just tried. Let's see if it helps.

**Comment by ttutisani** [comment]
I love how easy it is to change things in the PR 😄

**Comment by ttutisani** [comment]
I fixed a couple of things in the md file. Please let me know if you have any concerns. If not, I will merge.

**Comment by JornWildt** [comment]
No concerns from here. Looks great.

**Pull request merged**
